version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mongo-connection-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bds9zolxdlbk"
s3_prefix = "mongo-connection-test"
region = "eu-west-2"
profile = "joe"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
